steps:
    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['cp', '${_PATH_TO_ENV}', '.env']
    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['cp', '${_PATH_TO_STORAGE_CREDENTIALS}', 'storage-credentials.json']
    - name: 'gcr.io/cloud-builders/gsutil'
      args: ['cp', '${_PATH_TO_FIREBASE_CREDENTIALS}', 'firebase-credentials.json']
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/${_PROJECT_ID}/test-ubuntu-image', '.' ]
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'push', 'gcr.io/${_PROJECT_ID}/test-ubuntu-image']